<a href="https://colab.research.google.com/github/navap3206-debug/hello-world/blob/main/T03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratorio de regresión

## Significancia de factores

|                |   |
:----------------|---|
| **Nombre**     | Carlos Santiago Nava Pulido  |
| **Fecha**      | 10/01/2026  |
| **Expediente** | 756213  |

Descarga el archivo de publicidad y carga los datos (Advertising.csv).

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from sklearn.linear_model import LinearRegression


In [4]:
#Analizamos el dataframe
files = files.upload()
data = pd.read_csv('Advertising.csv')
data.head(5)

Saving Advertising.csv to Advertising.csv


,Unnamed: 0,TV,radio,newspaper,sales
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9


In [5]:
#Creamos las matrices y reacomodamos
matrix = (data[['TV', "radio", 'newspaper', 'sales']]).to_numpy()
matrix_x = (matrix[:, 0:3]).reshape(-1,3)
vec_y = (matrix[:, 3]).reshape(-1,1)


In [6]:
matrix_x

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

In [7]:
vec_y

array([[22.1],
       [10.4],
       [ 9.3],
       [18.5],
       [12.9],
       [ 7.2],
       [11.8],
       [13.2],
       [ 4.8],
       [10.6],
       [ 8.6],
       [17.4],
       [ 9.2],
       [ 9.7],
       [19. ],
       [22.4],
       [12.5],
       [24.4],
       [11.3],
       [14.6],
       [18. ],
       [12.5],
       [ 5.6],
       [15.5],
       [ 9.7],
       [12. ],
       [15. ],
       [15.9],
       [18.9],
       [10.5],
       [21.4],
       [11.9],
       [ 9.6],
       [17.4],
       [ 9.5],
       [12.8],
       [25.4],
       [14.7],
       [10.1],
       [21.5],
       [16.6],
       [17.1],
       [20.7],
       [12.9],
       [ 8.5],
       [14.9],
       [10.6],
       [23.2],
       [14.8],
       [ 9.7],
       [11.4],
       [10.7],
       [22.6],
       [21.2],
       [20.2],
       [23.7],
       [ 5.5],
       [13.2],
       [23.8],
       [18.4],
       [ 8.1],
       [24.2],
       [15.7],
       [14. ],
       [18. ],
       [ 9.3],
       [ 9

**¿Hay alguna relación entre el presupuesto para publicidad y las ventas?**

Nuestra primera meta debe ser determinar si hay evidencia en los datos de que haya una asociación entre estas variables.

- ¿Por qué? ¿Qué resultaría si nos diéramos cuenta de la falta de relación entre el presupuesto de publicidad y las ventas?

Debido a que entrenamos las regresiones mediante muestras, debemos asegurarnos de que el comportamiento de las muestras tenga una relación significativa con la población.  Si nos dieramos cuenta de que existiera  falta de información no podríamos utilizar estos datos para interpolar ni extrapolar en caso de realizar una regresión.

**¿Qué tan fuerte es esta relación?**
Asumiendo que existe esta relación, ¿nos sirve conocer el impacto que tiene invertir en publicidad en las ventas?

Si, porque nos permitiria desarrollar estrategías donde ser mejore la repartición de recursos según el peso que represente o en todo caso evitar invertir y abandonar la estrategia.

**¿Cuáles medios están asociados con las ventas? ¿Qué tan grande es la asociación entre un medio específico y las ventas?**

Hay 3 medios distintos en los datos. ¿Sirve invertir en los 3? ¿Conviene más invertir sólo en uno?

**¿Qué tan seguros estamos de que podríamos predecir ventas futuras?**

**¿La relación es lineal?**

**¿Hay sinergia entre estos medios?**

Puede ser que gastar \\$50,000 en publicidad y otros \\$50,000 en radio es mejor opción que gastar \\$100,000 en televisión. A esto le llamamos efecto de interacción.

Podemos usar regresión lineal para responder todas estas preguntas.

Realiza una regresión lineal:

$$ \text{ventas} \approx \beta_0 + (\beta_1)(\text{TV})$$

In [8]:
matrix_TV = matrix[:, 0].reshape(-1,1)
matrix_TV

array([[230.1],
       [ 44.5],
       [ 17.2],
       [151.5],
       [180.8],
       [  8.7],
       [ 57.5],
       [120.2],
       [  8.6],
       [199.8],
       [ 66.1],
       [214.7],
       [ 23.8],
       [ 97.5],
       [204.1],
       [195.4],
       [ 67.8],
       [281.4],
       [ 69.2],
       [147.3],
       [218.4],
       [237.4],
       [ 13.2],
       [228.3],
       [ 62.3],
       [262.9],
       [142.9],
       [240.1],
       [248.8],
       [ 70.6],
       [292.9],
       [112.9],
       [ 97.2],
       [265.6],
       [ 95.7],
       [290.7],
       [266.9],
       [ 74.7],
       [ 43.1],
       [228. ],
       [202.5],
       [177. ],
       [293.6],
       [206.9],
       [ 25.1],
       [175.1],
       [ 89.7],
       [239.9],
       [227.2],
       [ 66.9],
       [199.8],
       [100.4],
       [216.4],
       [182.6],
       [262.7],
       [198.9],
       [  7.3],
       [136.2],
       [210.8],
       [210.7],
       [ 53.5],
       [261.3],
       [

In [9]:
lr_TV = LinearRegression(fit_intercept=True)
lr_TV.fit(matrix_TV, vec_y)
lr_TV.coef_,lr_TV.intercept_

(array([[0.04753664]]), array([7.03259355]))

In [10]:
lr_TV.score(matrix_TV, vec_y)

0.611875050850071

### Verificando la precisión de nuestros coeficientes estimados

Recuerda que en el mundo real hay ruidos y errores de medición. Siempre se asume que la verdadera relación entre $X$ y $Y$ es $$Y = \beta_0 + \beta_1 X + \epsilon$$

Se asume que el término de error es independiente de $X$ (el error siempre es el mismo sin importar el valor de $X$). Este modelo describe a la *línea de regresión de la población*, que es la mejor aproximación de la verdadera relación entre $X$ y $Y$. Cuando usamos mínimos cuadrados encontramos la *línea de mínimos cuadrados*.

¿Cuál es la diferencia entre población y muestra?

Una población posee un comportamiento bien definido con una distribución invariable, una muestra es una agrupación de datos perteneciente a una población los cuales se asume según una distribucíon normal poseen una media similar a la de la población, por eso mismo se pueden inferir comportamientos a partir de muestras.

¿Cuál crees que sea la diferencia entre hacer una regresión con todos los datos de la población y una muestra de ella?

La población entrenaria una regresión en la que es seguro un comportamiento similar a los esperado, en cambio si obtienes una muestra no puedes saber si representa correctamente a la población, aspi que posterior debes asegurarte que la muestra sea significativa y pertenesca a la distribución correcta.

La línea de regresión de la población no se puede observar. El concepto de comparar estas líneas es una extensión natural del acercamiento estadístico estándar de usar información de una muestra para estimar características de una población grande.

Imagina que quieres encontrar la altura promedio de un mexicano $\mu$. Medir a todos y cada uno de los mexicanos en situaciones similares, con la misma regla, mismo operador, y otras incontables formas de minimizar la variación de la medida es una tarea imposible. Lo que podemos asumir es que $\hat{\mu} = \bar{y}$. La media poblacional y la media muestral son diferentes, pero la media muestral es usualmente un buen estimado.

De la misma manera, como no contamos con el 100% de la información para hacer una regresión, los coeficientes $\beta_0$ y $\beta_1$ son desconocidos. Podemos estimarlos usando mínimos cuadrados, encontrando $\hat{\beta_0}$ y $\hat{\beta_1}$. Puede que las muestras que tengamos en ese momento estén un poco por encima de la media, pero otras muestras en otro momento puede que estén debajo de la media. En general, esperamos que el promedio de las aproximaciones $\hat{\mu}$ aproxime a $\mu$.

Esto lleva a la pregunta: ¿qué tan cercanos son nuestros coeficientes estimados a los verdaderos coeficientes? Utilizamos el concepto de error estándar para evaluar esto.

$$ \text{Var}(\hat{\mu})=\text{SE}(\hat{\mu})^2 = \frac{\sigma^2}{n} $$

Donde $\sigma$ es la desviación estándar de cada una de las observaciones $y_i$ de $Y$. El error estándar nos dice la cantidad promedio que el estimado difiere del valor verdadero. Podemos ver en la fórmula que entre más observaciones tengamos el error se hace más pequeño. Las fórmulas para errores estándar de $\hat{\beta_0}$ y $\hat{\beta_1}$ son:

$$ \text{SE}(\hat{\beta_0})^2 = \sigma^2 [\frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^n (x_i - \bar{x})^2}]$$

$$ \text{SE}(\hat{\beta_1})^2 = \frac{\sigma^2}{\sum_{i=1}^n (x_i - \bar{x})^2}$$

$$ \sigma^2 = \text{Var}(\epsilon) = \text{RSE}^2 = \frac{\text{RSS}}{n-p}$$

Para que estas fórmulas sean validas asumimos que los errores $\epsilon_i$ tienen varianza común $\sigma^2$ y que no están correlacionados.

Calcula los errores estándar de los coeficientes

In [12]:
#PARA CONSEGUIR LAS VARIANZAS NECESITAMOS RSS
RSS = np.sum((vec_y - lr_TV.predict(matrix_TV))**2)
p = 2 #Hay dos coeficientes
var_TV = RSS/(len(vec_y)-p) #en este caso son dos
var_TV

np.float64(10.618841328946218)

In [26]:
#SACAMOS STANDARD ERROR DE B0
SE_TV_B_0 = (var_TV)*((1/len(vec_y)) + (((np.mean(matrix_TV)**2) / np.sum((matrix_TV - np.mean(matrix_TV))**2))))
SE_TV_B_0 = SE_TV_B_0**(1/2)
SE_TV_B_0


np.float64(0.4578429402734785)

In [27]:
#SACAMOS STANDARD ERROR DE B1

SE_TV_B_1 = var_TV/np.sum((matrix_TV- np.mean(matrix_TV))**2)
SE_TV_B_1 = SE_TV_B_1**(1/2)
SE_TV_B_1

np.float64(0.0026906071877968707)

Estos errores se pueden usar para calcular intervalos de confianza. Un intervalo de confianza del $95\%$ se define como un rango de valores en el cuál se encuentra el desconocido valor verdadero con un $95\%$ de probabilidad.

Otra forma de verlo es que si tomamos muestras repetidas y construimos un intervalo de confianza para cada una, el $95\%$ de los intervalos creados van a contener el valor verdadero. Para la regresión el intervalo de confianza del $95\%$ toma la forma:

$$ \hat{\beta_j} \pm 2\text{SE}(\hat{\beta_j})$$

Calcula los intervalos de confianza para los coeficientes estimados:

In [36]:
#INTERVALOS DE CONFIANZA PARA INTERCPTO
lm1_0 = lr_TV.intercept_ + 2*SE_TV_B_0

In [35]:
lm2_0 = lr_TV.intercept_ - 2*SE_TV_B_0

In [34]:
#INTERVALOS DE CONFIANZA PARA INTERCPTO
lm1_1 = lr_TV.coef_ + 2*SE_TV_B_1


In [37]:
lm2_1 = lr_TV.coef_ - 2*SE_TV_B_1

Los errores estándar también se usan para realizar pruebas de hipótesis. La prueba de hipótesis más común es probar la hipótesis nula de:

$$ H_0: \text{No hay relación entre } X \text{ y } Y \ \ \ \ (\beta_1=0)$$

contra la hipótesis alternativa:
$$ H_0: \text{Hay alguna relación entre } X \text{ y } Y \ \ \ (\beta_1 \neq 0)$$

Explica con tus palabras el significado de la hipótesis nula y la hipótesis alternativa.

La hipotesis nula es aquella afurmación que significaría que la muestra es parte de otrra distribución, miestras que la hiotesis alternatva confirmaría que los datos debería ser una distribución que imita cofrrectamente el comportamiento de la población.


Para probal la hipótesis nula debemos determinar si nuestro estimado $\hat{\beta_1}$ de $\beta_1$ está lo suficientemente alejado de cero para que podamos decir con confianza que este valor no es cero.

¿Qué tan lejos? Depende de qué tanta confianza tengamos en el estimado encontrado. Si nuestro error estándar es pequeño y nuestro estimado está alejado de cero podríamos decir que hay muy poca probabilidad de que el valor verdadero sea 0. En cambio, si nuestro error estándar es grande y nuestro estimado está muy cerca de cero, entonces podrías ser que el valor verdadero sea cero y que no haya relación entre las variables.

Se calcula un *estadístico t* dado por
$$ t = \frac{\hat{\beta_j} - \mu}{\text{SE}(\hat{\beta_j})} $$

donde $\mu$ es el valor contra el que queremos probar.

Calcula el estadístico t para tus coeficientes estimados, usando como referencia la prueba de hipótesis.

In [38]:
B1 = (lm1_0 ,lm2_1 )
B0 = (lm1_1 ,lm2_1 )

In [40]:
t0 = (lr_TV.intercept_ - 0)/SE_TV_B_0
t0

array([15.36027517])

In [41]:
t1 = (lr_TV.coef_ - 0)/SE_TV_B_1
t1

array([[17.6676256]])

La distribución t tiene forma de campana y se parece bastante a la distribución normal cuando $n > 30$. Ya sólo es cuestión de calcular la probabilidad de observar cualquier número tal que su valor absoluto sea igual o mayor que el valor absoluto del estadístico t calculado. En otras palabras:
$$ P(|x| \geq |t|) $$

A esta probabilidad la llamamos *p-value*. Un *p-value* pequeño indica que es poco probable que exista por puro azar una relación significativa entre predictor y respuesta, en caso de que no haya una asociación real entre predictor y respuesta. En otras palabras, el *p-value* te dice la probabilidad de que parezca que hay relación cuando no la hay.

Si el *p-value* es pequeño, inferimos que sí hay una asociación entre el predictor y la respuesta, y **rechazamos la hipótesis nula**.
  

¿Qué tan pequeño? Depende de la aplicación. Un valor muy común es del $5\%$.

Utiliza el siguiente código para calcular el *p-value* para tus coeficientes

`from scipy import stats`

`p_bj = 2*(1 - stats.t.cdf(np.abs(t_bj), n-p))`

In [42]:
from scipy import stats

In [44]:
p_b0 = 2*(1-stats.t.cdf(np.abs(t0),len(vec_y)-p))
p_b0

array([0.])

In [45]:
p_b1 = 2*(1-stats.t.cdf(np.abs(t1),len(vec_y)-p))
p_b1

array([[0.]])

¿Se rechaza la hipótesis nula? ¿Qué significa?

Rechazamos Ho y aprobamos H1 ya que Bj es diferente a 0, la muestra es representa significativamente  la población

Realiza otras dos regresiones. Ya tienes hecha la regresión de ventas dado el gasto en publicidad de TV. Realiza la regresión para gastos en radio y gastos en periódico. Organiza las respuestas para que debajo de esta celda se tenga:
- Título de regresión
- Coeficientes estimados
- Errores estándar de los coeficientes
- Intervalos de confianza
- Estadísticos t
- p-values
- Observaciones

***RADIO***

In [82]:
matrix_rd = matrix[:, 1].reshape(-1,1) #Seleccionamos los datos de radio
matrix_rd

array([[37.8],
       [39.3],
       [45.9],
       [41.3],
       [10.8],
       [48.9],
       [32.8],
       [19.6],
       [ 2.1],
       [ 2.6],
       [ 5.8],
       [24. ],
       [35.1],
       [ 7.6],
       [32.9],
       [47.7],
       [36.6],
       [39.6],
       [20.5],
       [23.9],
       [27.7],
       [ 5.1],
       [15.9],
       [16.9],
       [12.6],
       [ 3.5],
       [29.3],
       [16.7],
       [27.1],
       [16. ],
       [28.3],
       [17.4],
       [ 1.5],
       [20. ],
       [ 1.4],
       [ 4.1],
       [43.8],
       [49.4],
       [26.7],
       [37.7],
       [22.3],
       [33.4],
       [27.7],
       [ 8.4],
       [25.7],
       [22.5],
       [ 9.9],
       [41.5],
       [15.8],
       [11.7],
       [ 3.1],
       [ 9.6],
       [41.7],
       [46.2],
       [28.8],
       [49.4],
       [28.1],
       [19.2],
       [49.6],
       [29.5],
       [ 2. ],
       [42.7],
       [15.5],
       [29.6],
       [42.8],
       [ 9.3],
       [24

In [83]:
lr_rd = LinearRegression(fit_intercept=True) #Rwalizamos la regresión
lr_rd.fit(matrix_TV, vec_y)
lr_rd.coef_,lr_TV.intercept_

(array([[0.20249578]]), array([7.03259355]))

In [84]:
lr_rd.score(matrix_rd, vec_y)

0.33203245544529525

In [85]:
#PARA CONSEGUIR LAS VARIANZAS NECESITAMOS RSS
RSS = np.sum((vec_y - lr_rd.predict(matrix_rd))**2)
p = 2 #Hay dos coeficientes
var_rd = RSS/(len(vec_y)-p) #en este caso son dos
var_rd

np.float64(18.275149237500443)

In [86]:
#SACAMOS STANDARD ERROR DE B0
SE_rd_B_0 = (var_rd)*((1/len(vec_y)) + (((np.mean(matrix_rd)**2) / np.sum((matrix_rd - np.mean(matrix_rd))**2))))
SE_rd_B_0 = SE_rd_B_0**(1/2)
SE_rd_B_0

np.float64(0.5629004962718711)

In [87]:
#SACAMOS STANDARD ERROR DE B1
SE_rd_B_1 = var_rd/np.sum((matrix_rd- np.mean(matrix_rd))**2)
SE_rd_B_1 = SE_rd_B_1**(1/2)
SE_rd_B_1

np.float64(0.020411306360090635)

In [89]:
#INTERVALOS DE CONFIANZA PARA INTERCPTO
lm1_rd_0 = lr_rd.intercept_ + 2*SE_rd_B_0

In [90]:
lm2_rd_0 = lr_rd.intercept_ - 2*SE_rd_B_0

In [91]:
#INTERVALOS DE CONFIANZA PARA INTERCPTO
lm1_rd_1 = lr_rd.coef_ + 2*SE_rd_B_1

In [92]:
lm2_rd_1 = lr_rd.coef_ - 2*SE_rd_B_1

In [93]:
#INTERVALOS
B1_rd = (lm1_0 ,lm2_1 )
B0_rd = (lm1_1 ,lm2_1 )

In [103]:
#ESTADISTICO
t0_rd = (lr_rd.intercept_ - 0)/SE_rd_B_0


t0_rd

array([16.54224531])

In [109]:
t1_rd = (lr_rd.coef_ - 0)/SE_rd_B_1
t1_rd

array([[9.92076547]])

In [110]:
#PRUEBA DE HIPOTESIS
p_b0_rd = 2*(1-stats.t.cdf(np.abs(t0_rd),len(vec_y)-p))
p_b0
P_b1_rd = 2*(1-stats.t.cdf(np.abs(t1_rd),len(vec_y)-p))
print(p_b0
,P_b1_rd)


[0.] [[0.]]


***NEWSPAPER***

In [111]:
matrix_nw = matrix[:, 2].reshape(-1,1) #Separmaos los datos newspaper
matrix_nw

array([[ 69.2],
       [ 45.1],
       [ 69.3],
       [ 58.5],
       [ 58.4],
       [ 75. ],
       [ 23.5],
       [ 11.6],
       [  1. ],
       [ 21.2],
       [ 24.2],
       [  4. ],
       [ 65.9],
       [  7.2],
       [ 46. ],
       [ 52.9],
       [114. ],
       [ 55.8],
       [ 18.3],
       [ 19.1],
       [ 53.4],
       [ 23.5],
       [ 49.6],
       [ 26.2],
       [ 18.3],
       [ 19.5],
       [ 12.6],
       [ 22.9],
       [ 22.9],
       [ 40.8],
       [ 43.2],
       [ 38.6],
       [ 30. ],
       [  0.3],
       [  7.4],
       [  8.5],
       [  5. ],
       [ 45.7],
       [ 35.1],
       [ 32. ],
       [ 31.6],
       [ 38.7],
       [  1.8],
       [ 26.4],
       [ 43.3],
       [ 31.5],
       [ 35.7],
       [ 18.5],
       [ 49.9],
       [ 36.8],
       [ 34.6],
       [  3.6],
       [ 39.6],
       [ 58.7],
       [ 15.9],
       [ 60. ],
       [ 41.4],
       [ 16.6],
       [ 37.7],
       [  9.3],
       [ 21.4],
       [ 54.7],
       [

In [112]:
lr_nw = LinearRegression(fit_intercept=True)
lr_nw.fit(matrix_nw, vec_y)
lr_nw.coef_,lr_nw.intercept_

(array([[0.0546931]]), array([12.35140707]))

In [113]:
#PARA CONSEGUIR LAS VARIANZAS NECESITAMOS RSS
RSS = np.sum((vec_y - lr_nw.predict(matrix_nw))**2)
p = 2 #Hay dos coeficientes
var_nw = RSS/(len(vec_y)-p) #en este caso son dos
var_nw

np.float64(25.933356283393632)

In [114]:
#SACAMOS STANDARD ERROR DE B0
SE_nw_B_0 = (var_nw)*((1/len(vec_y)) + (((np.mean(matrix_nw)**2) / np.sum((matrix_nw - np.mean(matrix_nw))**2))))
SE_nw_B_0 = SE_nw_B_0**(1/2)
SE_nw_B_0

np.float64(0.6214201876094345)

In [115]:
#SACAMOS STANDARD ERROR DE B1
SE_nw_B_1 = var_nw/np.sum((matrix_nw- np.mean(matrix_nw))**2)
SE_nw_B_1 = SE_nw_B_1**(1/2)
SE_nw_B_1


np.float64(0.016575721876358165)

In [108]:
#INTERVALOS DE CONFIANZA PARA INTERCPTO
lm1_nw_0 = lr_nw.intercept_ + 2*SE_nw_B_0

In [116]:
lm2_nw_0 = lr_nw.intercept_ - 2*SE_nw_B_0

In [117]:
#INTERVALOS DE CONFIANZA PARA INTERCPTO
lm1_nw_1 = lr_nw.coef_ + 2*SE_nw_B_1

In [118]:
lm2_nw_1 = lr_nw.coef_ - 2*SE_nw_B_1


In [119]:
#INTERVALOS
B1_nw = (lm1_0 ,lm2_1 )
B0_nw = (lm1_1 ,lm2_1 )

In [120]:
#ESTADISTICO
t0_nw = (lr_nw.intercept_ - 0)/SE_nw_B_0
t0_nw

array([19.87609562])

In [121]:
t1_nw = (lr_nw.coef_ - 0)/SE_nw_B_1
t1_nw

array([[3.29959074]])

In [122]:
#PRUEBA DE HIPOTESIS
p_b0_nw = 2*(1-stats.t.cdf(np.abs(t0_nw),len(vec_y)-p))
p_b0
P_b1_nw = 2*(1-stats.t.cdf(np.abs(t1_nw),len(vec_y)-p))
print(p_b0
,P_b1_rd)


[0.] [[0.]]


NO POSEEMOS EVIDENCI DE QUE LA MUESTRA NO SEA SIGNIFICATIVA


## Regresión lineal múltiple

En lugar de hacer una regresión para cada factor independiente, quizás se puede extender el modelo para que tenga varios factores dentro:

$$ Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + ... + \beta_p X_p + \epsilon $$

Para nuestro ejemplo de publicidad:

$$ \text{sales} = \beta_0 + \beta_1 (\text{TV}) + \beta_2 (\text{radio}) + \beta_3 (\text{newspaper}) + \epsilon $$

Utiliza la librería `statsmodels` para realizar la regresión. Por defecto la librería statsmodels no toma en cuenta el intercepto ($\beta_0$), por lo que se tendrá que agregar una columna de unos de tamaño *n* a la matriz X.

`import statsmodels.api as sm`

`ols = sm.OLS(Y, X)`

`results = ols.fit()`

`results.summary()`

In [127]:
import statsmodels.api as SM
X2 = SM.add_constant(matrix_x) #CONCADENAR
model = SM.OLS(vec_y,X2) #MODELO MINIMOS CUADRADOS ORDINARIOS
results = model.fit() #OPTIMIZA
print(results.summary())#RESUME

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Mon, 02 Feb 2026   Prob (F-statistic):           1.58e-96
Time:                        22:41:31   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.0

¿Qué diferencias puedes observar entre los *p-values* de una regresión múltiple y los encontrados en las regresiones simples? ¿Por qué crees que existen estas diferencias?

Los p values individuales resultan ser optimos para realizar una regresión de confianza, cunado realizamos el analisis conjunto o multiple newspaper resulta no tener una rlació n significativa como para confiar en la regesión.

## Referencia

James, G., Witten, D., Hastie, T., Tibshirani, R.,, Taylor, J. (2023). An Introduction to Statistical Learning with Applications in Python. Cham: Springer. ISBN: 978-3-031-38746-3